Transition of Power
badgerloop-software/pod-embedded pull request #120
Opened 2020-09-04 17:18 UTC by EUdds

2020-09-04 17:22 UTC, ezraboley requested changes

2020-09-04 17:22 UTC, ezraboley commented on README.md
> +*Developers: Eric Udlis, Rohan Daruwala, Ezra Boley, Nic Hodlofski, Daniel Kouchekinia, Ezra Freeman*
Unacceptable

2020-09-15 04:29 UTC, EUdds commented
@ezraboley I would like to revisit this

2020-09-18 16:01 UTC, ezraboley approved these changes

2020-09-18 16:02 UTC, merged